project_id = "bpxawsodojccnovxkfcp"

[functions.agente-ia]
verify_jwt = false

[functions.elevenlabs-tts]
verify_jwt = false

[functions.elevenlabs-voices]
verify_jwt = false

[functions.analise-financeira]
verify_jwt = false

[functions.tts-multi]
verify_jwt = false

[functions.google-calendar]
verify_jwt = false

[functions.create-user]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.import-excel]
verify_jwt = false

[functions.integracao-enviar]
verify_jwt = false

[functions.integracao-webhook]
verify_jwt = false
